import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Slideshow from '../components/slideshow'
import About from '../components/About'
import Gallery from '../components/Gallery'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       < Slideshow/>
       <br></br>
       <br></br>
       <About/>
       <Gallery/>

     
    </div>
  )
}
